//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdraw
    {
        public int WithdrawID { get; set; }
        public decimal WithdrawAmount { get; set; }
        public System.DateTime WithdrawDate { get; set; }
        public string WithdrawName { get; set; }
    }
}
